// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtlcynzrhchbuvwktokn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0bGN5bnpyaGNoYnV2d2t0b2tuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY4NDc5NDQsImV4cCI6MjA1MjQyMzk0NH0.qDB4NB1gSvdfEq2Sz2EhJl5ZeRuEHh-rLqvvDQ0VVx8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);